services:
  web:
    build: .
    ports:
      - "80:3000"
  postgres:
    image: postgres:17.5-alpine3.21
    ports:
      - 5432:5432
    volumes:
      - /pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres