daemon off;

events {
    worker_connections 1024;
}

http {
	server {
	    listen 80;
	    server_name space4art.live;
	    return 301 https://$server_name$request_uri;
	}

	server {
	    listen 443 ssl;
	    server_name space4art.live;

	    ssl_certificate ./cert.pem;
	    ssl_certificate_key ./key.pem;

	    location / {
	        proxy_pass http://localhost:3000; # Assuming your SvelteKit app runs on port 5000
	        proxy_http_version 1.1;
	        proxy_set_header Upgrade $http_upgrade;
	        proxy_set_header Connection 'upgrade';
	        proxy_set_header Host $host;
	        proxy_cache_bypass $http_upgrade;
	    }
	}
}
